# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class YamlDocs < Formula
  desc "Automatically generate markdown documentation for YAML configuration files"
  homepage "https://github.com/blakyaks/yaml-docs"
  version "0.0.13"

  on_macos do
    on_intel do
      url "https://github.com/blakyaks/yaml-docs/releases/download/v0.0.13/yaml-docs_0.0.13_Darwin_x86_64.tar.gz"
      sha256 "414ba2ed5d27a4262672551652eb8860179de31a31bd65a13f2d5e971542c59f"

      def install
        bin.install "yaml-docs"
      end
    end
    on_arm do
      url "https://github.com/blakyaks/yaml-docs/releases/download/v0.0.13/yaml-docs_0.0.13_Darwin_arm64.tar.gz"
      sha256 "27f40209d63c5aefe54648d649d845293af540ccec65eb469c5603d2c0d61e37"

      def install
        bin.install "yaml-docs"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/blakyaks/yaml-docs/releases/download/v0.0.13/yaml-docs_0.0.13_Linux_x86_64.tar.gz"
        sha256 "893b77759510c7465aa69e5f97b85c02c21aab08a4f0ee869d5f62dbeb294e2a"

        def install
          bin.install "yaml-docs"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/blakyaks/yaml-docs/releases/download/v0.0.13/yaml-docs_0.0.13_Linux_arm6.tar.gz"
        sha256 "a22be4afad6bc39880bc09d96709df45f14150de99e5cb92cd3c61e0648a8c45"

        def install
          bin.install "yaml-docs"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/blakyaks/yaml-docs/releases/download/v0.0.13/yaml-docs_0.0.13_Linux_arm64.tar.gz"
        sha256 "6d9a90a570f87c1dc4046e403a158cb368c7d5521bd000abce4a539406140514"

        def install
          bin.install "yaml-docs"
        end
      end
    end
  end

  test do
    system "#{bin}/yaml-docs --version"
  end
end
