# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class YamlDocs < Formula
  desc "Automatically generate markdown documentation for YAML configuration files"
  homepage "https://github.com/blakyaks/yaml-docs"
  version "0.0.6"

  on_macos do
    on_intel do
      url "https://github.com/blakyaks/yaml-docs/releases/download/v0.0.6/yaml-docs_0.0.6_Darwin_x86_64.tar.gz"
      sha256 "00f9dc004ea49482007ae61a2c4698cab5baa7c5997e8ea80b023e0687ef197b"

      def install
        bin.install "yaml-docs"
      end
    end
    on_arm do
      url "https://github.com/blakyaks/yaml-docs/releases/download/v0.0.6/yaml-docs_0.0.6_Darwin_arm64.tar.gz"
      sha256 "0795eb987d67a99b6b5f2844ef35c06c250256110e46e0fa0b022e7b15c9469c"

      def install
        bin.install "yaml-docs"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/blakyaks/yaml-docs/releases/download/v0.0.6/yaml-docs_0.0.6_Linux_x86_64.tar.gz"
        sha256 "35f8ca0a46e32046090a8dec438a92830c51d7076ae43799a689306364c88108"

        def install
          bin.install "yaml-docs"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/blakyaks/yaml-docs/releases/download/v0.0.6/yaml-docs_0.0.6_Linux_arm6.tar.gz"
        sha256 "795e5a44776f6417e92d98ac5bf8d5cad07bd76a1013dc0adbda906efbee9fa4"

        def install
          bin.install "yaml-docs"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/blakyaks/yaml-docs/releases/download/v0.0.6/yaml-docs_0.0.6_Linux_arm64.tar.gz"
        sha256 "c79f0f49dd64e8a1e2c1e21fb3579bec8904b06bec28955150fccfbb84bc5a11"

        def install
          bin.install "yaml-docs"
        end
      end
    end
  end

  test do
    system "#{bin}/yaml-docs --version"
  end
end
